select APELLIDO,OFICIO,SALARIO,DEPT_NO FROM EMP;

select EMP.APELLIDO,EMP.OFICIO,EMP.SALARIO,EMP.DEPT_NO,DEPT.DNOMBRE
from EMP
inner join DEPT
on EMP.DEPT_NO = DEPT.DEPT_NO
where SALARIO > 300000;


select HOSPITAL.NOMBRE as NOMBREHOSPITAL,SALA.NOMBRE AS NOMBRESALA
from HOSPITAL
inner join SALA
on HOSPITAL.HOSPITAL_COD = SALA.HOSPITAL_COD;

